apiVersion: apps/v1
kind: Deployment
metadata:
  name: gatewayapi-deployment
  labels:
    app: mygateway
spec:
  replicas: 2
  selector:
    matchLabels:
      app: mygateway
  template:
    metadata:
      labels:
        app: mygateway
    spec:
      containers:
      - name: mygatewaycnt
        image: mygateway:latest
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 80
        volumeMounts:
        - mountPath: "/app/file_share"
          name: task-pv-storage
        env:
        - name: DataDirectory
          value: "/app"
      volumes:
      - name: task-pv-storage
        persistentVolumeClaim:
          claimName: task-pv-claim
# kubectl apply -f GatewayApi_depl.yaml
# https://kubernetes.io/docs/tasks/configure-pod-container/configure-persistent-volume-storage/