apiVersion: v1
kind: Service
metadata:
  name: mywebapp-service
spec:
  selector:
    app: webapp
  ports:
    - protocol: TCP
      port: 50080
      targetPort: 80
# kubectl apply -f WebApp_service.yaml
# No need as we have creted WebApp_loadbalancer_service.yaml as Load balancer