apiVersion: apps/v1
kind: Deployment
metadata:
  name: webapp-deployment
  labels:
    app: webapp
spec:
  replicas: 2
  selector:
    matchLabels:
      app: webapp
  template:
    metadata:
      labels:
        app: webapp
    spec:
      containers:
      - name: mywebappcnt
        image: mywebapp:latest
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 80
        env:
        - name: ApiGatewayUrl
          valueFrom:
            configMapKeyRef:
              name: mywebapp-config
              key: APIGATEWAY-URL
        - name: ApiTenantKey
          valueFrom:
            secretKeyRef:
              name: mywebapp-secret
              key: APITENANT-KEY
        - name: ASPNETCORE_ENVIRONMENT
          value: Development

# kubectl apply -f WebApp_depl.yaml
